import { useSyncExternalStore } from "react";
import type { ThreadMessage, ThreadMessageLike } from "@assistant-ui/react";
import { dropCompaction, LEGACY_SUMMARY_STORAGE, summaryStorageKey } from "./compaction";
import { getApiKey, newId } from "./session";

/**
 * Browser-side store for multiple chat sessions.
 *
 * Layout in localStorage:
 *   agent_sessions_v1            index: SessionMeta[]
 *   agent_active_session         id of the open chat
 *   agent_session_<id>_msgs      that chat's messages
 *   agent_session_<id>_docs      that chat's uploaded-document chips
 *   agent_session_<id>_summary   that chat's condensed-history summary (lib/compaction)
 *
 * A session's id is also the `session_id` sent to the server, which keys the
 * in-memory document index there — so uploaded documents belong to one chat.
 *
 * A brand-new chat is only a "draft" id until something is actually sent or
 * uploaded; only then does it enter the index, so the sidebar never fills up
 * with empty chats.
 */

export type SessionMeta = {
  id: string;
  title: string;
  /** "fallback" = trimmed first question; "ai" = generated by /chat/title. */
  titleSource: "fallback" | "ai";
  /** The first user message (trimmed). Input for the AI title. */
  question: string;
  /** First turn finished — eligible for an AI title. */
  replied: boolean;
  createdAt: number;
  updatedAt: number;
};

export type DocEntry = { name: string; chunks: number };

type Snapshot = {
  sessions: readonly SessionMeta[];
  activeId: string;
  /** Ids of sessions with a reply currently generating (compaction included). */
  running: readonly string[];
  /** Running sessions that are stuck waiting for the user (a failed compaction
   * offering Retry / Continue anyway). The model is idle for these. */
  awaiting: readonly string[];
  /** `running` minus `awaiting`: chats that are actually using the model. */
  busy: readonly string[];
  /** Bumps every time a reply finishes in this page load. */
  turnTick: number;
  storageFull: boolean;
};

const INDEX_KEY = "agent_sessions_v1";
const ACTIVE_KEY = "agent_active_session";
const LEGACY_HISTORY = "agent_history_v2";
const LEGACY_DOCS = "agent_docs";
const LEGACY_SESSION_ID = "agent_session_id";
const msgsKey = (id: string) => `agent_session_${id}_msgs`;
const docsKey = (id: string) => `agent_session_${id}_docs`;

export const DEFAULT_TITLE = "New chat";
const QUESTION_MAX_CHARS = 300;
const FALLBACK_TITLE_CHARS = 40;

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function readJson<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : fallback;
  } catch {
    return fallback;
  }
}

/** Plain text of a message, whether it is a string or a list of parts. */
export function textOf(message: { content: unknown } | undefined): string {
  const content = message?.content;
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content
      .filter((p): p is { type: "text"; text: string } => p?.type === "text" && typeof p.text === "string")
      .map((p) => p.text)
      .join("\n\n");
  }
  return "";
}

function clip(text: string, max = QUESTION_MAX_CHARS): string {
  return text.replace(/\s+/g, " ").trim().slice(0, max);
}

/** Immediate title shown until (or unless) the AI title arrives. */
export function fallbackTitle(question: string): string {
  const flat = clip(question);
  if (!flat) return DEFAULT_TITLE;
  if (flat.length <= FALLBACK_TITLE_CHARS) return flat;
  const cut = flat.slice(0, FALLBACK_TITLE_CHARS);
  const space = cut.lastIndexOf(" ");
  return `${space > FALLBACK_TITLE_CHARS / 2 ? cut.slice(0, space) : cut}…`;
}

function isMeta(value: unknown): value is SessionMeta {
  const v = value as Partial<SessionMeta> | null;
  return Boolean(v && typeof v.id === "string" && typeof v.title === "string");
}

// ---------------------------------------------------------------------------
// state
// ---------------------------------------------------------------------------

let sessions: SessionMeta[] = [];
let activeId = "";
let running: string[] = [];
let awaiting: string[] = [];
let turnTick = 0;
let storageFull = false;
let snapshot: Snapshot;

const docsCache = new Map<string, DocEntry[]>();
/** Ids deleted in this page load — pending saves for them must not resurrect them. */
const deleted = new Set<string>();
const listeners = new Set<() => void>();

function buildSnapshot(): Snapshot {
  return {
    sessions,
    activeId,
    running,
    awaiting,
    busy: running.filter((id) => !awaiting.includes(id)),
    turnTick,
    storageFull,
  };
}

function emit() {
  snapshot = buildSnapshot();
  listeners.forEach((l) => l());
}

function subscribe(listener: () => void) {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

function write(key: string, value: string): boolean {
  try {
    localStorage.setItem(key, value);
    if (storageFull) {
      storageFull = false;
      emit();
    }
    return true;
  } catch (err) {
    console.warn("[sessions] could not write to localStorage:", err);
    if (!storageFull) {
      storageFull = true;
      emit();
    }
    return false;
  }
}

function remove(key: string) {
  try {
    localStorage.removeItem(key);
  } catch {
    // nothing useful to do
  }
}

function persistIndex() {
  write(INDEX_KEY, JSON.stringify(sessions));
}

function persistActive() {
  try {
    localStorage.setItem(ACTIVE_KEY, activeId);
  } catch {
    // losing the "last open chat" pointer is harmless
  }
}

function patchSession(id: string, patch: Partial<SessionMeta>) {
  sessions = sessions.map((s) => (s.id === id ? { ...s, ...patch } : s));
}

function mostRecent(): SessionMeta | undefined {
  return [...sessions].sort((a, b) => b.updatedAt - a.updatedAt)[0];
}

// ---------------------------------------------------------------------------
// one-time migration from the single-chat layout
// ---------------------------------------------------------------------------

function migrateLegacy() {
  if (localStorage.getItem(INDEX_KEY) !== null) return;

  const legacyMessages = readJson<ThreadMessageLike[]>(LEGACY_HISTORY, []);
  const legacyDocs = readJson<DocEntry[]>(LEGACY_DOCS, []);
  const legacyId = localStorage.getItem(LEGACY_SESSION_ID);
  const legacySummary = localStorage.getItem(LEGACY_SUMMARY_STORAGE);

  if (legacyId && (legacyMessages.length > 0 || legacyDocs.length > 0)) {
    const question = clip(textOf(legacyMessages.find((m) => m.role === "user")));
    const now = Date.now();
    const meta: SessionMeta = {
      id: legacyId,
      title: fallbackTitle(question),
      titleSource: "fallback",
      question,
      replied: legacyMessages.some((m) => m.role === "assistant"),
      createdAt: now,
      updatedAt: now,
    };
    try {
      localStorage.setItem(msgsKey(legacyId), JSON.stringify(legacyMessages));
      localStorage.setItem(docsKey(legacyId), JSON.stringify(legacyDocs));
      if (legacySummary) localStorage.setItem(summaryStorageKey(legacyId), legacySummary);
      localStorage.setItem(INDEX_KEY, JSON.stringify([meta]));
    } catch {
      return; // couldn't write — leave the old data untouched and retry next load
    }
  }
  remove(LEGACY_HISTORY);
  remove(LEGACY_DOCS);
  remove(LEGACY_SESSION_ID);
  remove(LEGACY_SUMMARY_STORAGE);
}

function init() {
  migrateLegacy();
  sessions = readJson<unknown[]>(INDEX_KEY, []).filter(isMeta);
  const stored = localStorage.getItem(ACTIVE_KEY);
  activeId = stored && sessions.some((s) => s.id === stored) ? stored : newId();
  snapshot = buildSnapshot();
}

init();

// ---------------------------------------------------------------------------
// reading
// ---------------------------------------------------------------------------

export function useSessionStore(): Snapshot {
  return useSyncExternalStore(subscribe, () => snapshot);
}

export function useSessionDocs(id: string): DocEntry[] {
  return useSyncExternalStore(subscribe, () => getDocs(id));
}

export function getDocs(id: string): DocEntry[] {
  let docs = docsCache.get(id);
  if (!docs) {
    docs = readJson<DocEntry[]>(docsKey(id), []);
    docsCache.set(id, docs);
  }
  return docs;
}

/** Messages for mounting a chat. A reply that was mid-stream when the page
 * closed has no end state, so it is shown as cancelled rather than running. */
export function loadMessages(id: string): ThreadMessageLike[] {
  return readJson<ThreadMessageLike[]>(msgsKey(id), []).map((m) =>
    m.role === "assistant" && (m.status?.type === "running" || m.status?.type === "requires-action")
      ? { ...m, status: { type: "incomplete", reason: "cancelled" } }
      : m,
  );
}

/** The id of a chat other than `id` that is using the model right now, if any. */
export function getOtherRunningId(id: string): string | null {
  return running.find((r) => r !== id && !awaiting.includes(r)) ?? null;
}

// ---------------------------------------------------------------------------
// writing
// ---------------------------------------------------------------------------

export function saveMessages(id: string, messages: readonly ThreadMessage[]) {
  if (deleted.has(id) || !sessions.some((s) => s.id === id)) return;
  write(msgsKey(id), JSON.stringify(messages));
}

export function setDocs(id: string, docs: DocEntry[]) {
  if (deleted.has(id)) return;
  docsCache.set(id, docs);
  if (docs.length > 0) ensureSession(id);
  write(docsKey(id), JSON.stringify(docs));
  emit();
}

/** A server restart loses every session's uploaded documents; messages stay. */
export function invalidateAllDocs() {
  const ids = new Set([...sessions.map((s) => s.id), ...docsCache.keys()]);
  for (const id of ids) {
    docsCache.set(id, []);
    remove(docsKey(id));
  }
  emit();
}

/** Adds a draft to the index (no-op if it is already there). */
function ensureSession(id: string, question = "") {
  if (deleted.has(id) || sessions.some((s) => s.id === id)) return;
  const now = Date.now();
  sessions = [
    {
      id,
      title: fallbackTitle(question),
      titleSource: "fallback",
      question: clip(question),
      replied: false,
      createdAt: now,
      updatedAt: now,
    },
    ...sessions,
  ];
  persistIndex();
  emit();
}

/** Called whenever a chat has a user message: registers the session and
 * records the first question (once). */
export function noteUserMessage(id: string, question: string) {
  const meta = sessions.find((s) => s.id === id);
  if (!meta) {
    ensureSession(id, question);
    return;
  }
  if (meta.question || deleted.has(id)) return;
  const q = clip(question);
  if (!q) return;
  patchSession(id, { question: q, title: meta.titleSource === "fallback" ? fallbackTitle(q) : meta.title });
  persistIndex();
  emit();
}

export function touch(id: string) {
  if (!sessions.some((s) => s.id === id)) return;
  patchSession(id, { updatedAt: Date.now() });
  persistIndex();
  emit();
}

export function noteTurnFinished(id: string) {
  turnTick += 1;
  if (sessions.some((s) => s.id === id)) {
    patchSession(id, { replied: true, updatedAt: Date.now() });
    persistIndex();
  }
  emit();
}

export function setAiTitle(id: string, title: string) {
  const meta = sessions.find((s) => s.id === id);
  if (!meta || meta.titleSource === "ai") return;
  patchSession(id, { title, titleSource: "ai" });
  persistIndex();
  emit();
}

export function setRunning(id: string, isRunning: boolean) {
  const has = running.includes(id);
  if (isRunning === has) return;
  running = isRunning ? [...running, id] : running.filter((r) => r !== id);
  emit();
}

/** A running chat is waiting on the user (failed compaction): it should not
 * hold the model "busy" for the other chats. */
export function setAwaitingChoice(id: string, isAwaiting: boolean) {
  const has = awaiting.includes(id);
  if (isAwaiting === has) return;
  awaiting = isAwaiting ? [...awaiting, id] : awaiting.filter((a) => a !== id);
  emit();
}

export function selectSession(id: string) {
  if (id === activeId || !sessions.some((s) => s.id === id)) return;
  activeId = id;
  persistActive();
  emit();
}

export function newChat() {
  if (!sessions.some((s) => s.id === activeId)) return; // already on a blank draft
  activeId = newId();
  persistActive();
  emit();
}

export function deleteSession(id: string) {
  const hadDocs = getDocs(id).length > 0;
  deleted.add(id);
  sessions = sessions.filter((s) => s.id !== id);
  running = running.filter((r) => r !== id);
  awaiting = awaiting.filter((a) => a !== id);
  docsCache.delete(id);
  dropCompaction(id); // stops a compaction still in flight and removes the stored summary
  remove(msgsKey(id));
  remove(docsKey(id));
  persistIndex();
  if (activeId === id) {
    activeId = mostRecent()?.id ?? newId();
    persistActive();
  }
  emit();
  // Only worth a request (which could wake a scaled-to-zero instance) if the
  // server may actually hold documents for this session.
  if (hadDocs) {
    void fetch("/kb/clear", {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-api-key": getApiKey() },
      body: JSON.stringify({ session_id: id }),
    }).catch(() => {
      // best effort — the server drops it on its next restart anyway
    });
  }
}
